apiVersion: v1
kind: Namespace
metadata:
  name: services
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service-1
  namespace: services
  labels:
    app: java-service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service-1
  template:
    metadata:
      labels:
        app: java-service-1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyMemory: "50Mi"
    spec:
      containers:
      - name: java-app
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: java-service-1
  namespace: services
  labels:
    app: java-service-1
spec:
  selector:
    app: java-service-1
  ports:
  - port: 8080
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service-2
  namespace: services
  labels:
    app: java-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service-2
  template:
    metadata:
      labels:
        app: java-service-2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyMemory: "50Mi"
    spec:
      containers:
      - name: java-app
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: java-service-2
  namespace: services
  labels:
    app: java-service-2
spec:
  selector:
    app: java-service-2
  ports:
  - port: 8080
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service-3
  namespace: services
  labels:
    app: java-service-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service-3
  template:
    metadata:
      labels:
        app: java-service-3
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyMemory: "50Mi"
    spec:
      containers:
      - name: java-app
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: java-service-3
  namespace: services
  labels:
    app: java-service-3
spec:
  selector:
    app: java-service-3
  ports:
  - port: 8080
    targetPort: 9090
