apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-agent-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes", "nodes/stats", "nodes/proxy", "events", "services", "endpoints", "persistentvolumeclaims", "persistentvolumes", "resourcequotas", "replicationcontrollers"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-agent-role-binding
subjects:
- kind: ServiceAccount
  name: otel-agent-collector
  namespace: opentelemetry-operator-system
- kind: ServiceAccount
  name: otel-gateway-collector
  namespace: opentelemetry-operator-system
roleRef:
  kind: ClusterRole
  name: otel-agent-role
  apiGroup: rbac.authorization.k8s.io
